
DELETE http://localhost:3003/api/blogs/63d363cf5a49994d461abc76
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpeXVzaCIsImlkIjoiNjNkMzViOWY0ZDUzMTZlM2E5MTNjYzI5IiwiaWF0IjoxNjc0Nzk2NjczfQ.STZ8zfWDj8ubzYSK6HNTR_xwPHAKeK5UR4XsXNIBP2o

###
DELETE http://localhost:3003/api/blogs/63d363cf5a49994d461abc76
Authorization: bearer wrongauthorizationtoken44444

###
DELETE http://localhost:3003/api/blogs/63d363cf5a49994d461abc76
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpeXVzaDEiLCJpZCI6IjYzZDM1YmM1NGQ1MzE2ZTNhOTEzY2MyZCIsImlhdCI6MTY3NDc5Njc4N30.ASTCgRsYmgQWYdKYXZHr3MfBzq4U-VBfETJSjWvZp4o

###
GET http://localhost:3003/api/blogs