POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "piyush",
    "password": "12345"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"piyush",
    "password":"wrong"
}